services:
  terraria:
    build: .
    environment:
      - version=1449    # the version of terraria server to use
      - save_delay=5    # the time in minute between each save (1-59)
    volumes:
      - ./worlds:/worlds
      - ./logs:/logs
      - ./config:/home/serverconfig.txt
    ports:
      - "7777:7777"
    restart: on-failure
